### ISSUE TITLE
Default value callable

### ISSUE THREAD

**Issue by ziima** [Genida/django-appsettings#17]
Add a possibility to use callable as a default value. Either allow callable to be used as value for `default` argument or define `get_default` method on `Setting` object.

I'd go with the first option.

**Comment by Pawamoy** [comment]
Yes, good idea. I should be able to implement this quickly.

**Comment by Pawamoy** [comment]
So, you can now give a callable as a default value. It will be called **by default** on all settings except `ObjectSetting`. You can change this behavior with the new parameter in setting: `call`. If `call` is True and `default` is a callable, return `default()`. Else return `default`. This parameter is important for `ObjectSetting`, because if you give the path to a function, you may not want it to be called!

**Comment by ziima** [comment]
I've tested it in refactor-properties-caching branch and it works well. Looking forward to see it in the new version.

**Comment by Pawamoy** [comment]
Yup, I guess you saw that I changed it a bit since my last message in this thread (`call` param now `call_default` to be more explicit, and I also added `transform_default` bool param).

The tests are up-to-date, now I have to update the CHANGELOG, the README and the docs

I think I will bump the major number, getting to 1.0.0 (no alpha anymore), unless you think the app is not ready for it.

**Comment by ziima** [comment]
I only used `StringSettings` so far. Personally, I'd go with 0.3 for now. When I use it for more settings than just the basic ones, I can provide better feedback.

`call_default` looks better.

**Comment by Pawamoy** [comment]
Released version 0.3.0 :)
