### ISSUE TITLE
Tweak style checks

### ISSUE THREAD

**Issue by ziima** [Genida/django-appsettings#38]
I suggest to do some minor modifications in style checks:
 * Use 120 chars per line. 80 is way too restrictive and 120 is sort of common value used in python projects.
 * Drop custom import sections. Pandas are not used at all, and Django is regular third party and should be handled as such.

**Comment by pawamoy** [comment]
1. Yeah I always kind of sticked to the 79 chars length restriction, but for big projects I usually increase it to 99. I don't mind putting it to 120. Also what do you think about using black for linting?

2. It was here because I generate my projects with a cookiecutter, but it's useless here, so let's remove pandas and treat Django as regular third party.

**Comment by ziima** [comment]
> Also what do you think about using black for formatting/linting?

I haven't actually ever seen it before. I haven't make an opinion yet.

**Comment by pawamoy** [comment]
I am improving the quality test suite. Will open a PR so you can review if needed.

**Comment by pawamoy** [comment]
So, the line length was increased to 120 and the isort custom import sections were removed with #45 and ad1ffcb0db2f88192891a0553840fd321362739a. Closing :slightly_smiling_face: !
